Update comment.yml

diff --git a/.github/workflows/comment.yml b/.github/workflows/comment.yml
--- a/.github/workflows/comment.yml
+++ b/.github/workflows/comment.yml
@@ -26,11 +26,11 @@ jobs:
      - name: Parse body
        id: parse
        run: |
-        grep "^Diff Regression projects:" text > temp || echo "No diff regression projects found"
-        sed 's/Diff Regression projects: //' temp > proj || echo "fail" > proj
+        grep "^Diff Regression projects:" text > temp || echo "fail" > temp
+        sed 's/Diff Regression projects: //' temp > proj || echo "No diff regression projects found"
         echo ::set-output name=proj_link::$(cat proj)
-        grep "^Diff Regression config:" text > temp || echo "No diff regression config found"
-        sed 's/Diff Regression config: //' temp > config || echo "fail" > config
+        grep "^Diff Regression config:" text > temp || echo "fail" > temp
+        sed 's/Diff Regression config: //' temp > config || echo "No diff regression config found"
         echo ::set-output name=config_link::$(cat config)
       
      - name: show info
